id: P9F4A671D
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: zh
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    f43474e92abd4006b772da58605f75ee:
      title: Advice for Alak Dongak
      parent: Advice
    d381e4b4fa0e462e9697b11b0eeb6d86:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    06d47a7f39094b0592a58070239d4019:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    1a5d19f2bb584c6eb1ea71dd33633116:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    3e0c46790c9f4f418f1f338617f5cf73:
      title: Yearning for Mountain Solitude
      parent: Advice
    b1d25cb0be7946f0b99257c3ad97d1fd:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    32e170fe6e384f08835349866e917c65:
      title: Biography of Patrul Rinpoche
      parent: Biography
    2c01dd5f8c644d4887a6ae47a74f1925:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    3ba1d11c4ec84bb58a08ad703b6d75a5:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    ed2e9103f0734729ba543068fe75fd79:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    030c0da815d3434595d6780b2a5c2c13:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    1ff263675f624cbdb303c2bf5b2d9385:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    249447678d3d4763bdfaefdf939fe32f:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    beed2ad966a747728e538555d008e31a:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    5a36d43693104f0ea449e14d4729c09d:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    d3331444d4fb48f2bbf27160220c3a2e:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    8e9a42506b0b4d90bdb1ec43b83c9a6b:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    24b20c252faa4172a9f2fba9138fcecd:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    4fe23cc566484a30bd21e41794e2dabd:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    d30573a2a76a4e3aa9e6afeb44caf77d:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    55044685660b44528e8817f6aaa5a9d7:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    762ea88723a64b9ea79c3e30b27c8ecb:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    cef6548a428246879b5dd348545b150f:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    ea76496ffbd34e46a8f721e1177cfa4a:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    e9275ab4002a4f729e00eb004ceabdac:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    127f522950c64458b558cb4169cbe597:
      title: Prayer to Machik Labdrön
      parent: Prayers
    dd7629d3373f4aa6bd588a228f23fa17:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    d689373d72de44dca102a7727b8f97b6:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    f192807743fc4a0f9eeac7c63a17ccd7:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    f75582c7f78643cdafe644ab69ea563b:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    4d697d2ba9444968a980859f82617e1d:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    7bba33c847b241b99a5cf105d5520eb0:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    2d952a261d5f436eb1ce4d5d60f947da:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    4bc9060de9bf4609bd6294b14c4336d0:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    88f85738b12c446699d4811ec5bce889:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    2cee055a812648a585f2eba9f924874f:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    c950268cfaf3404a940938419aa443f3:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    67cef0dec60c48de85420a5a7f3ac26e:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    2d54c86e76dd4ae9a6eb3d7705eca6d6:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.748630'
last_modified_at: '2022-03-01T01:13:56.748633'
